<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'CrudController\Mvc\Controller\AbstractCrudController'           => __DIR__ . '/src/CrudController/Mvc/Controller/AbstractCrudController.php',
  'CrudController\ControllerFactory\AbstractCrudControllerFactory' => __DIR__ . '/src/CrudController/ControllerFactory/AbstractCrudControllerFactory.php',
  'CrudController\Exception'                                       => __DIR__ . '/src/CrudController/Exception.php',
  'CrudController\Module'                                          => __DIR__ . '/src/CrudController/Module.php',
  'CrudController\Repository\CrudRepository'                       => __DIR__ . '/src/CrudController/Repository/CrudRepository.php',
  'CrudController\Repository\CrudRepositoryInterface'              => __DIR__ . '/src/CrudController/Repository/CrudRepositoryInterface.php',
  'CrudController\Listener\CrudControllerListener'                 => __DIR__ . '/src/CrudController/Listener/CrudControllerListener.php',
);
