<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Nicovogelaar\CrudController\Mvc\Controller\AbstractCrudController'           => __DIR__ . '/src/Mvc/Controller/AbstractCrudController.php',
  'Nicovogelaar\CrudController\ControllerFactory\AbstractCrudControllerFactory' => __DIR__ . '/src/ControllerFactory/AbstractCrudControllerFactory.php',
  'Nicovogelaar\CrudController\Exception'                                       => __DIR__ . '/src/Exception.php',
  'Nicovogelaar\CrudController\Module'                                          => __DIR__ . '/src/Module.php',
  'Nicovogelaar\CrudController\Repository\CrudRepository'                       => __DIR__ . '/src/Repository/CrudRepository.php',
  'Nicovogelaar\CrudController\Repository\CrudRepositoryInterface'              => __DIR__ . '/src/Repository/CrudRepositoryInterface.php',
  'Nicovogelaar\CrudController\Listener\CrudControllerListener'                 => __DIR__ . '/src/Listener/CrudControllerListener.php',
);
